name: aimart_dev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  awesome_card: ^1.1.7
  intl: ^0.18.1
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  pin_code_fields: ^7.4.0
  adaptive_theme: ^3.1.1
  flutter: 
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^0.8.6
  firebase_core: ^2.11.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  optimized_cached_image: ^3.0.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.11
  is_first_run: ^1.0.0
  algolia: ^1.1.1
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  http: ^0.13.5
  cloud_functions: ^4.2.0
  firebase_messaging: ^14.5.0
  async: ^2.8.2


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/

