name: aimart_dev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  awesome_card: ^1.1.7
  intl: ^0.17.0
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  pin_code_fields: ^7.4.0
  adaptive_theme: ^3.1.1
  flutter: 
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^0.8.6
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  optimized_cached_image: ^3.0.1
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^4.4.1+1
  is_first_run: ^1.0.0
  algolia: ^1.1.1
  google_maps_flutter: ^2.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/

