// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY4kZzuCL_J-fbot3tYgeOwduxidetC1s',
    appId: '1:985249804118:web:da4271d1e4c3b97d37b0f7',
    messagingSenderId: '985249804118',
    projectId: 'aimart-9d86d',
    authDomain: 'aimart-9d86d.firebaseapp.com',
    storageBucket: 'aimart-9d86d.appspot.com',
    measurementId: 'G-4S9DZ9XXG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPSeY_nTQLvq16mOq7zU8QMjdAkPQtdzI',
    appId: '1:985249804118:android:6558140c685157b637b0f7',
    messagingSenderId: '985249804118',
    projectId: 'aimart-9d86d',
    storageBucket: 'aimart-9d86d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_JlJ10QJoDxS-m08K3dkmVJRFS_1zmPA',
    appId: '1:985249804118:ios:427bfb0c706e76e337b0f7',
    messagingSenderId: '985249804118',
    projectId: 'aimart-9d86d',
    storageBucket: 'aimart-9d86d.appspot.com',
    iosClientId: '985249804118-oufg6ivatd883ut2c0f0qfa5qajq6va6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aimartDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_JlJ10QJoDxS-m08K3dkmVJRFS_1zmPA',
    appId: '1:985249804118:ios:427bfb0c706e76e337b0f7',
    messagingSenderId: '985249804118',
    projectId: 'aimart-9d86d',
    storageBucket: 'aimart-9d86d.appspot.com',
    iosClientId: '985249804118-oufg6ivatd883ut2c0f0qfa5qajq6va6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aimartDev',
  );
}
